name: Create GitHub Project

on:
  workflow_dispatch:

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_TOKEN | gh auth login --with-token

    - name: Create new repository
      run: |
        gh repo create my-new-repo --public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}