name: Called Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.build.outputs.build_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          echo 開発が実装
          echo "build_version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo $build_version