
name: Called Workflow

on:
  workflow_call:
    outputs:
      build_version:
        value: ${{ jobs.build.outputs.build_version }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.build.outputs.build_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          build_version=$(git rev-parse --short HEAD)
          echo "build_version=$build_version" >> $GITHUB_OUTPUT
