name: CI

on:
 pull_request:
  branches:
    - main

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run test
        run: echo "Running test"