name: Check Workflow Status

on:
  workflow_dispatch:

jobs:
  check_workflow_status:
    runs-on: ubuntu-latest

    steps:
      - name: Get workflow ID
        id: get_workflow_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ワークフロー名を指定
          WORKFLOW_NAME="deproy"
          WORKFLOW_ID=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | jq -r ".workflows[] | select(.name == \"$WORKFLOW_NAME\") | .id")
          echo "Workflow ID: $WORKFLOW_ID"
          echo "workflow_id=$WORKFLOW_ID" >> $GITHUB_ENV

      - name: Get latest workflow run status
        id: get_latest_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.workflow_id }}/runs")
          LATEST_STATUS=$(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[0].conclusion')
          echo "Latest workflow run status: $LATEST_STATUS"
          echo "latest_status=$LATEST_STATUS" >> $GITHUB_ENV

      - name: Check status
        run: |
          if [ "${{ env.latest_status }}" != "success" ]; then
            echo "The latest workflow did not succeed!"
            exit 1
          else
            echo "The latest workflow succeeded."
          fi
