name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@4
    - name: small test
      id: small-test
      uses: ./.github/plugin/small-test.yml