name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: aaa
    uses: ./.github/workflows/build.yml

  small-test:
    name: bbb
    need: [build-and-test]
    uses: ./.github/workflows/small-test.yml

  small-test-notification:
    name: ccc
    need: [small-test]
    uses: ./.github/workflows/small-test-notification.yml
    with:
      conclusion: ${{ needs.small-test.outcome }}
      