name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

  call-small-test:
    uses: ./.github/plugin/small-test.yml
    with:
      example_input: "Hello, World!"