name: Main Workflow

on:
  workflow_dispatch:

jobs:
  name: test
  runs-on: ubuntu-latest
  steps:
    - name: small test
      id: small-test
      uses: ./.github/plugin/small-test.yml
    - name: 完了
      if: always()
      uses: ./.github/plugin/gate.yml
      with:
        check: ${{ steps.small-test.outcome}}