name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: aaa
    uses: ./.github/workflows/build.yml

  small-test:
    name: bbb
    needs: [build-and-test]
    uses: ./.github/workflows/small-test.yml

  small-test-notification:
    name: ccc
    needs: [small-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify
        run: echo "${{ needs.build-and-test.result }}"
