name: Main Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

  call-small-test:
    needs: [build-and-test]
    uses: ./.github/workflows/small-test.yml
    with:
      example_input: "Hello, World!"