
name: Revert on off

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert_and_create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Find latest merge commit
      id: find_merge
      run: |
        latest_merge_commit=$(git log main --pretty=format:"%H" -n 1)
        echo "merge_commit=$latest_merge_commit" >> $GITHUB_ENV

    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.REVIW_TOKEN }}" | gh auth login --with-token
        
    - name: Toggle Enforcement OFF
      run: |
        gh api \
          -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository }}/branches/main/protection \
          -F enforce_admins=false \
          -F required_status_checks='{"strict": true, "contexts": []}' \
          -F required_pull_request_reviews=null \
          -F restrictions=null

    - name: Revert latest merge commit
      if: env.merge_commit != ''
      run: |
        git checkout main
        git revert -m 1 ${{ env.merge_commit }}
        git push origin HEAD:main

    - name: Toggle Enforcement OFF
      run: |
        gh api \
          -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository }}/branches/main/protection \
          -F enforce_admins=true \
          -F required_status_checks='{"strict": true, "contexts": []}' \
          -F required_pull_request_reviews=null \
          -F restrictions=null

    - name: Create and push bugfix branch
      run: |
        git checkout -b bugfix/test
        git push origin bugfix/test
