name: Auto-approve PR for revert branches

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the PR branch starts with 'revert-'
        run: |
          if [[ "${{ github.head_ref }}" == revert-* ]]; then
            echo "Branch starts with 'revert-', automatically approving."
            echo "approve=true" >> $GITHUB_ENV
          else
            echo "Branch does not start with 'revert-', review required."
            echo "approve=false" >> $GITHUB_ENV

      - name: Automatically approve PR if branch starts with 'revert-'
        if: env.approve == 'true'
        run: |
          echo "Approving PR because the branch starts with 'revert-'."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event":"APPROVE"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"

      - name: Fail if review is required
        if: env.approve == 'false'
        run: |
          echo "Review is required for this PR."
          exit 1
