name: Called Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: |
          echo Input value: ${{ inputs.example_input }}