
name: Called Workflow

on:
  workflow_call:
    inputs:
      conclusion:
        required: true
        type: string

jobs:
  small-test-notify:
    name: Small Test Notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Display Received Value
        id: small-test
        run: |
          echo "受け取った値を表示: ${{ inputs.conclusion }}"
