name: Called Workflow

on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string

jobs:
  small-test:
    name: Small Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: small test実行
        id: small-test
        run: |
          echo 開発が実装
          echo build_version: ${{ inputs.build_version }}"