name: Called Workflow

on:
  workflow_call:
    inputs:
      pull_request_ref:
        required: true
        type: string

jobs:
  small-test:
    name: Small Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pull_request_ref }}
      - name: small test実行
       id: small-test
       run: |
        echo 開発が実装